### PR TITLE
Truncates filenames if they exceed OS limit

### PR DESCRIPTION
**Pull request by helrond**
Gets the maximum filename length and truncates the name of the renamed file if it exceeds the max allowable by the underlying OS. Addresses https://github.com/archivematica/Issues/issues/1586

There is not a test which covers this new functionality because I couldn't find a logical place to test - the more atomic `change_names` function (which I attempted to test first) just replaces Unicode, it doesn't examine filename length. The `change_paths` function (which is what I want to test) isn't really tested anywhere, except maybe implicitly via `change_objects` but I was having a hard time untangling all of that. One thought I had was to pull lines 63-74 out into a new function called `construct_file_title` or something that would be more easily testable (and wouldn't require writing files to disk). Would welcome thoughts on the best approach.

### CODE REVIEW

**Comment by replaceafill** [comment]
@helrond I just merged https://github.com/artefactual/archivematica/pull/1812 to address the linting problem your PR shows in the GitHub workflows.

Could you please rebase you branch on top of the current `qa/1.x` branch when you have a chance? Thanks!

**Comment by helrond** [comment]
@replaceafill OK, took a couple of tries for me to resolve things but linting is passing now.

**Comment by replaceafill** [comment]
@helrond I just ran the Archivematica acceptance tests on your branch and found there's a problem in a different client script that reuses the `change_path` function that has been changed:

```
hack-archivematica-mcp-client-1  | *** Completed job: #<changesipname_v0.0; exit=1; code=success uuid=1e2c81a0-c460-4e47-8767-ad0fbbbb58ca
hack-archivematica-mcp-client-1  | =============== STDOUT ===============
hack-archivematica-mcp-client-1  | 
hack-archivematica-mcp-client-1  | =============== END STDOUT ===============
hack-archivematica-mcp-client-1  | =============== STDERR ===============
hack-archivematica-mcp-client-1  | change_path() missing 1 required positional argument: 'max_filename'Traceback (most recent call last):
hack-archivematica-mcp-client-1  |   File "/src/src/MCPClient/lib/job.py", line 113, in JobContext
hack-archivematica-mcp-client-1  |     yield
hack-archivematica-mcp-client-1  |   File "/src/src/MCPClient/lib/clientScripts/change_sip_name.py", line 61, in call
hack-archivematica-mcp-client-1  |     dst = change_path(SIPDirectory)
hack-archivematica-mcp-client-1  | TypeError: change_path() missing 1 required positional argument: 'max_filename'
hack-archivematica-mcp-client-1  | 
hack-archivematica-mcp-client-1  | =============== END STDERR ===============
```

See https://github.com/artefactual/archivematica/blob/374da6162bee1d58cde8d2c796cde5551afde00a/src/MCPClient/lib/clientScripts/change_sip_name.py#L34

**Comment by helrond** [comment]
@replaceafill OK I've resolved that issue, but tests are failing for some reason related to Codecov availability (I think).

**Review by replaceafill — APPROVED** [review]
Thank you @helrond!

The acceptance tests are currently failing because of https://github.com/archivematica/Issues/issues/1582 but I think we can merge this.

**Comment by replaceafill** [comment]
https://github.com/artefactual/archivematica/commit/b5d15aa43e9ae8279f2043fc5af6cdd6e4fd227d in the `stable/1.13.x` branch.

**Pull request merged**
