### PR TITLE
Fix index_aip_and_files() call from mgmt cmd (stable/1.9.x)

### PR DESCRIPTION
**Pull request by hakamine**
Fix index_aip_and_files() invocation from
rebuild_elasticsearch_aip_index_from_files management command.

Connected to https://github.com/archivematica/Issues/issues/595

Cherry-pick of https://github.com/artefactual/archivematica/pull/1381 (protected branch requires approving review)

### CODE REVIEW

**Review by jraddaoui — APPROVED** [review]
Thanks @hakamine! I personally think there is no need to create a PR to cherry-pick an already reviewed commit, unless you want an extra pair of eyes in case there was a lot of conflicts involved.

**Comment by hakamine** [comment]
@jraddaoui Thank you. The reason I created a separate PR is because github did not let me just cherry-pick onto stable/1.9.x and push, got the following error:
<pre>
remote: error: GH006: Protected branch update failed for refs/heads/stable/1.9.x.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:artefactual/archivematica
 ! [remote rejected]   stable/1.9.x -> stable/1.9.x (protected branch hook declined)
error: failed to push some refs to 'git@github.com:artefactual/archivematica'
</pre>
Do you know a way to avoid this problem?

**Comment by jraddaoui** [comment]
Thanks for letting me know @hakamine, I didn't know about that hook.

**Comment by jraddaoui** [comment]
And I guess we probably don't want to avoid it, it's a good security measure.

**Pull request merged**
