### PR TITLE
ArchivesSpace: find_by_field uses new endpoint

### PR DESCRIPTION
**Pull request by Hwesta**
find_by_field renamed to find_by_id and uses new ArchivesSpace plugin endpoint. This should return no more than 1 result, and no false positives.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Rename the ArchivistsToolkitClient at the same time, maybe?

:+1: otherwise

**Comment by jhsimpson** [comment]
I think the ArchivistsToolkit change should happen in its own pull request.

**Comment by mistydemeo** [comment]
Sounds good. :+1:

**Comment by Hwesta** [comment]
> I think the ArchivistsToolkit change should happen in its own pull request.

The ATK change was made initially to keep the APIs of the ATK and ArchivesSpace classes in sync.  The change I amended into the commit does the same thing - renames the function to keep the APIs the same. The ATK version still raises a NotImplementedError.  @jhsimpson do you still want it in a separate PR?

**Comment by mistydemeo** [comment]
:shipit: 

It's probably easier for us to actually implement this in ATK now, but we can reserve _that_ for a followup PR.

**Comment by jhsimpson** [comment]
yes, this PR looks good to me as is.  I tested it and the new endpoint is working as expected.

:+1:

**Comment by Hwesta** [comment]
Double-committed to qa/1.5.x as d12f3f1d351ae4a23824500c485b5fa7450ea181

**Pull request merged**
