### PR TITLE
Use PREMIS 3 and fixes for old AIPs

### PR DESCRIPTION
**Pull request by sevein**
Connects to https://github.com/archivematica/Issues/issues/24.
Connects to https://github.com/archivematica/Issues/issues/370.
Connects to https://github.com/archivematica/Issues/issues/504.

### CODE REVIEW

**Comment by hakamine** [comment]
@sevein I am currently working on rebasing this branch on top of current qa/1.x. I have a couple of questions (probably related):
- Should I squash into a single commit? (not sure if this is a good idea, too many changes in different parts of the code for a single commit?)
- Code in qa/1.x is already formatted by black. If not squashing, should I add a commit on top for black changes?

**Comment by sevein** [comment]
Don't squash, please! Rebasing that way would be hard (impossible?). Try the procedure explained here: https://github.com/artefactual/archivematica-storage-service/pull/439.

**Comment by hakamine** [comment]
@sevein probably should have asked earlier! 😓 I did a rebase (without squashing) but just did the black re-formatting at the end, resulting branch is https://github.com/artefactual/archivematica/commits/dev/issue-24-handle-old-aips-rebase (didn't want to overwrite the original branch without asking first). Should I better redo (i.e. do the black formatting at each commit)?

**Comment by sevein** [comment]
Actually I think you did the right thing. I think that rebasing like I did in SS was doable only because black was at the tip, but you had to deal with further conflicts like the bagit stuff. I think you nailed it!

**Review by hakamine — APPROVED** [review]
I rebased both AM and SS dev/issue-24-handle-old-aips branches on top of the current qa/1.x and deployed on a test server. I ran an import, a reindex, and reingest of AM68 without errors. I think the dev branches are ready to merge to AM a/1.x and SS qa/0.x (then a more extensive testing/refining can be done)

**Comment by sevein** [comment]
@hakamine, thanks for doing that! Please merge away!

**Pull request merged**
