### PR TITLE
Update appraisal tab webpack file

### PR DESCRIPTION
**Pull request by jraddaoui**
Includes changes from the following pull requests:

https://github.com/artefactual-labs/appraisal-tab/pull/150
https://github.com/artefactual-labs/appraisal-tab/pull/152
https://github.com/artefactual-labs/appraisal-tab/pull/153
https://github.com/artefactual-labs/appraisal-tab/pull/155
https://github.com/artefactual-labs/appraisal-tab/pull/156

### CODE REVIEW

**Review by sevein — APPROVED** [review]

**Comment by Hwesta** [comment]
This was closed - was it merged?

This will have to be updated to include #566 before it can be merged.

**Comment by jraddaoui** [comment]
I can't find the merged commit in qa/1.x nor qa/1.6.x, and I don't know how the branch got deleted.

It looks like #566 was merged in qa/1.6.x so, please, let me know if I should recreate this PR against that branch. I've pushed the branch again and added the changes from https://github.com/artefactual-labs/appraisal-tab/pull/156.

**Comment by sevein** [comment]
@jraddaoui maybe you pushed to github.com? It's happened to me before.

**Comment by sevein** [comment]
IMO opening a pull request is unnecessary.

**Comment by jraddaoui** [comment]
Moved to https://github.com/artefactual/archivematica/pull/574

**Comment by jraddaoui** [comment]
Ok, I'll ask to @Hwesta where this should be merged, thanks!

**Pull request closed without merging**
