### PR TITLE
Add a get_first_location() helper with better error messages

### PR DESCRIPTION
**Pull request by alexwlchan**
For https://github.com/archivematica/Issues/issues/1103

### CODE REVIEW

**Comment by alexwlchan** [comment]
This is ready for review, but it seems to be having an issue with the NPM build. Anybody have any ideas?

**Comment by replaceafill** [comment]
Looks like a temporary problem with Travis. I restarted the build and it passed this time.

**Review by sevein — APPROVED** [review]

**Comment by sevein** [comment]
@alexwlchan, please rebase when you have a chance and I'll merge.

**Comment by alexwlchan** [comment]
Rebased.

**Pull request merged**
