### PR TITLE
Create METS continue on error

### PR DESCRIPTION
**Pull request by helenst**
Addresses https://github.com/archivematica/Issues/issues/620

### CODE REVIEW

**Review by ross-spencer — COMMENTED** [review]
LGTM! :+1:

**Review by ross-spencer — APPROVED** [review]

**Comment by ross-spencer** [comment]
Hi @helenst I think to merge this into `qa/1.x` I need to ask you to rebase against the current `qa/1.x` and then I'll merge from the rebased branch. I can't think of another way to do it without creating another branch on here, but let me know if you have another approach?

**Comment by helenst** [comment]
After a rebase, it started breaking a (presumably newly added) test, `test_create_file_sec`. Which was failing because the number of file entries in the xml didn't match the number of files on disk. It was passing in `qa/1.x` because the `FileDoesNotExist` exception was thrown due to a missing entry in the fixture and because this was on an iteration other than the first one, `f` was already defined but holding the entry from the previous iteration, resulting in incorrect xml output (rather than outright failure). I've fixed it by adding the entry to the fixture. I don't know if this is the correct fix, what do you think?

Also, now it is failing due to linting issues which come from qa/1.x.

**Comment by ross-spencer** [comment]
@helenst yep, looks like the correct fix to me. That was a new test, and also, that structmap happened to be the last structmap xml I added to the test! I hope we get the opportunity to better isolate these tests/fixtures but it's gonna be fiddly! 

Will try and rebase and merge this work asap!

**Review by ross-spencer — APPROVED** [review]

**Comment by ross-spencer** [comment]
Hi @helenst I've been wrestling with Git to try and rebase and merge this without either:

1. Asking you to rebase it again so I can merge it.
2. Creating a new PR against it to then merge it.

Both seem sub-optimal with the work already in place. I can't figure out another way though so can I ask you to do 1. again for me? 

I'll try and get this merged asap again today. 

Do you have a preferred approach to merges in future? Is this approach okay? Can you think of another way to do this with the protections we currently have on the qa branch?

**Comment by helenst** [comment]
@ross-spencer This is now rebased against the latest qa/1.x - I'm really not sure how to do things any better though in terms of merging :)

**Comment by ross-spencer** [comment]
Merged!! :tada: :tada: :tada: 

As long as it's not too patience challenging then it's okay I guess and our branches aren't always moving so fast.

**Pull request merged**
