### PR TITLE
Models: use longblob in SIPArrange

### PR DESCRIPTION
**Pull request by sevein**
Convert `varchar` columns into `longblob` (`SIPArrange`).

This is connected to https://github.com/archivematica/Issues/issues/53.
Relates to https://github.com/artefactual/archivematica/pull/509.

### CODE REVIEW

**Comment by sevein** [comment]
@jhsimpson: changing the types in `SIPArrange` fixes the problem. But I have one question for you. I can't add the unique key to `original_location` now that it's a BLOB because it also expects the key length. I don't know at the moment how can I do that via Django or if it's a good idea at all. Thoughts? Also the use of the new type may have a performance impact.

Similar issue with key length here: https://github.com/artefactual/archivematica/pull/509.

This model is used in a number of places, should we investigate further? Or is this PR good as it is?

```
src/MCPClient/lib/clientScripts/create_mets_v2.py
src/MCPClient/lib/clientScripts/failed_sip_cleanup.py
src/MCPClient/lib/clientScripts/post_store_aip_hook.py
src/dashboard/src/components/access/views.py
src/dashboard/src/components/api/views.py
src/dashboard/src/components/filesystem_ajax/views.py
src/dashboard/src/components/ingest/views.py
```

**Comment by sevein** [comment]
How is SIPArrange used?

---

src/MCPClient/lib/clientScripts/create_mets_v2.py

	SIPArrange.objects.filter(sip_id=sip_uuid).values_list('arrange_path', 'level_of_description')

src/MCPClient/lib/clientScripts/failed_sip_cleanup.py

	models.SIPArrange.objects.filter(sip_id=sip_uuid).delete()

src/MCPClient/lib/clientScripts/post_store_aip_hook.py

	models.SIPArrange.objects.filter(file_uuid__in=file_uuids).update(aip_created=True)
	models.SIPArrange.objects.filter(file_uuid__in=file_uuids).values_list('transfer_uuid', flat=True)
	models.SIPArrange.objects.filter(transfer_uuid=transfer_uuid).filter(aip_created=True).values_list('file_uuid', flat=True)

src/dashboard/src/components/access/views.py

	SIPArrange.objects.get(arrange_path=os.path.join(mapping.arrange_path, '')

src/dashboard/src/components/api/views.py

	models.SIPArrange.objects.filter(arrange_path__in=(path, path + '/'), sip_created=False)

src/dashboard/src/components/filesystem_ajax/views.py

	SIPArrange.objects.filter(sip_created=False).filter(arrange_path__startswith=filepath)
	SIPArrange.objects.filter(arrange_path__startswith=filepath).delete()
	SIPArrange.objects.filter(arrange_path__startswith=sourcepath)
	SIPArrange.objects.filter(arrange_path=sourcepath).update(arrange_path=destination + os.path.basename(sourcepath))
	SIPArrange.objects.filter(sip_created=False).filter(aip_created=False).filter(arrange_path__startswith=base_path).order_by('arrange_path')
	SIPArrange.objects.get_or_create(original_path=None, arrange_path=os.path.join(path, ''), file_uuid=None)
	SIPArrange.objects.create(original_path=entry['original_path'], arrange_path=entry['arrange_path'], file_uuid=entry['file_uuid'], transfer_uuid=entry['transfer_uuid'])

src/dashboard/src/components/ingest/views.py

	SIPArrange.objects.filter(original_path__endswith=path['relative_path'])

From the above I think it's safe to stop using the index in `original_path` and have one in `file_uuid` instead as we discussed.

**Comment by sevein** [comment]
This is ready. What took me the longest was to have a migration where the unique key index on `original_path` could be removed when the name of the index is `original_path` but also when it has arbitrary names assigned by Django - which could happen if you downgrade your database and then upgrade it again.

This is how it'd look like after the migration:

```sql
CREATE TABLE `main_siparrange` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_path` longblob,
  `arrange_path` longblob NOT NULL,
  `file_uuid` varchar(36) DEFAULT NULL,
  `transfer_uuid` varchar(36) DEFAULT NULL,
  `sip_created` tinyint(1) NOT NULL,
  `aip_created` tinyint(1) NOT NULL,
  `level_of_description` varchar(2014) NOT NULL,
  `sip_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `main_siparrange_file_uuid_41cbc240ae7e78b5_uniq` (`file_uuid`),
  KEY `main_siparrange_2664b5aa` (`sip_id`),
  CONSTRAINT `main_siparrange_sip_id_601574f35f1ea7ec_fk_SIPs_sipUUID` FOREIGN KEY (`sip_id`) REFERENCES `SIPs` (`sipUUID`)
```

If you unapply th emigration, e.g.:

    docker-compose exec archivematica-dashboard /src/dashboard/src/manage.py migrate main 0058

Then:

```sql
CREATE TABLE `main_siparrange` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_path` varchar(255) DEFAULT NULL,
  `arrange_path` varchar(255) NOT NULL,
  `file_uuid` varchar(36) DEFAULT NULL,
  `transfer_uuid` varchar(36) DEFAULT NULL,
  `sip_created` tinyint(1) NOT NULL,
  `aip_created` tinyint(1) NOT NULL,
  `level_of_description` varchar(2014) NOT NULL,
  `sip_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `main_siparrange_original_path_326864576e0e0fb2_uniq` (`original_path`),
  KEY `main_siparrange_2664b5aa` (`sip_id`),
  CONSTRAINT `main_siparrange_sip_id_601574f35f1ea7ec_fk_SIPs_sipUUID` FOREIGN KEY (`sip_id`) REFERENCES `SIPs` (`sipUUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

The name of the index is not `original_path` anymore but `drop_original_path_unique_key` will be able to handle that.

**Comment by jraddaoui** [comment]
Hi @sevein, this looks good to me!

But, from your previous update, I wonder how is the `DEFAULT NULL` removed from the `original_path` column in the migration, I couldn't see that in the code ...

**Review by jraddaoui — APPROVED** [review]

**Comment by sevein** [comment]
@jraddaoui good catch - apparently `BLOB` and `TEXT` columns can't have default values.

https://dev.mysql.com/doc/refman/8.0/en/blob.html
> BLOB and TEXT columns cannot have DEFAULT values.

**Pull request merged**
