### PR TITLE
Add session auth. to dashboard API

### PR DESCRIPTION
**Pull request by jraddaoui**
And restore auth. checks removed in 520eb63

### CODE REVIEW

**Comment by sevein** [comment]
Is it safe to do this? Could an authenticated client take advantage of it and move files around for example?

**Comment by jraddaoui** [comment]
Hi @sevein, I guess it's not safe, but it was like that in stable/1.6.x and I'm not sure if the dashboard and/or other client apps use these endpoints. I could try to add user session auth. in them for the dashboard requests but it may break requests made from other places.

**Comment by sevein** [comment]
Then I would call that a bug and I think it would justify the change even if it's backward incompatible.
@jhsimpson @ross-spencer @jrwdunham, what do you think?

**Comment by jrwdunham** [comment]
I think these endpoints should allow both api key- and session-based authentication.

**Review by sevein — APPROVED** [review]
Excellent, thanks for doing this @jraddaoui!

**Comment by jraddaoui** [comment]
0af67bee24acf19e62cbb3ada28356393bb9e400 in stable/1.7.x

**Pull request merged**
