### PR TITLE
Search: tune elasticsearch module for AIP indexing speed

### PR DESCRIPTION
**Pull request by sevein**
Indexing times are ~100x faster (index_aip) with some simple changes, broken into small commits. Highest impact seen after moving to lxml, parsing AIP METS document only once and bulk insert (in batches of 50 docs). For a 1000 xml transfer, indexing time goes from 240s to ~2.5s.

This PR also removes METS embedding in "aips" docs. The `view raw` link has been removed as a result. See https://github.com/artefactual/archivematica/issues/1199 for more.

### CODE REVIEW

**Review by cole — APPROVED** [review]
Approved, this all makes sense and looks good to me.

One thing (for another PR) is do we need to store METS details in the `aipfiles` index? If not we could remove that as well.

**Comment by sevein** [comment]
Thanks @cole. We make METS details available in `aipfiles` so it's easier for users to find files from the archival storage tab via different properties. But it could be cleaned up (e.g. remove XML namespaces) and have a simpler structure/mapping that doesn't follow what's in the METS strictly.

**Comment by hakamine** [comment]
@sevein (not sure if this information is relevant to the PR, just mentioning it because of the switch from ElementTree to lxml; please ignore if unrelated) in the past I had "broken" AIP indexing when trying to replace the library `xml.etree.ElementTree` with `lxml.etree` in `archivematicaCommon/elasticSearchFunctions` (ref. [AM issue 619](https://github.com/archivematica/Issues/issues/619#issuecomment-487190700) ) (had to revert back to ElementTree due to some mapping issues).

**Comment by sevein** [comment]
Ok thanks @hakamine, I'll investigate!

**Comment by sromkey** [comment]
@sevein can you suggest how we should test this for the 1.10.1 release?

**Comment by jraddaoui** [comment]
> @sevein (not sure if this information is relevant to the PR, just mentioning it because of the switch from ElementTree to lxml; please ignore if unrelated) in the past I had "broken" AIP indexing when trying to replace the library `xml.etree.ElementTree` with `lxml.etree` in `archivematicaCommon/elasticSearchFunctions` (ref. [AM issue 619](https://github.com/archivematica/Issues/issues/619#issuecomment-487190700) ) (had to revert back to ElementTree due to some mapping issues).

Thanks for noting this @hakamine and sorry for making you to change it back before. Check https://github.com/artefactual/archivematica/issues/1199#issuecomment-586312684 and https://github.com/artefactual/archivematica/pull/1571 for more info.

**Pull request merged**
