### PR TITLE
Added API endpoint to hide completed ingests

### PR DESCRIPTION
**Pull request by jrwdunham**

### CODE REVIEW

**Review by Hwesta — APPROVED** [review]
Looks good!  Will probably want changes if #521 comes in.

**Comment by hakamine** [comment]
Confirmed to be working in a client's testing server👍

**Comment by jrwdunham** [comment]
Cherry-picked to stable/1.5.x as 23258a01af2d882df9a8857fa8e03bfd9a77e6e2

**Comment by jrwdunham** [comment]
In qa/1.6.x as 95062110d1bc5654af0e7b8304c2b2e3ea456e1b

**Pull request merged**
