### PR TITLE
dev-helper: remove restart services

### PR DESCRIPTION
**Pull request by mistydemeo**
This also exists in the archivematica-devtools repository; suggest removing this extra copy to avoid maintaining two versions. If memory serves, the archivematica-devtools version is also slightly more up-to-date.

### CODE REVIEW

**Comment by Hwesta** [comment]
:+1: 

Alternately, have dev-helper call am restart-services.  Either works for me, since I use a fish function most of the time.

**Comment by mistydemeo** [comment]
Oh yeah, I didn't think of that. Do we want to make archivematica-devtools a requirement of running dev-helper?

**Comment by Hwesta** [comment]
Hmm, I don't really want AM to require devtools, but it's convenient that dev-helper restarts things to pick up all the updates that likely just happened, especially if you don't already know to do that.

**Comment by Hwesta** [comment]
Since we're moving to ansible for all deployments, am-devtools is pretty easy to install (and dev-helper is mostly deprecated).  I vote this gets merged.

**Pull request merged**
