### PR TITLE
display dropdown modal is options greater then 10

### PR DESCRIPTION
**Pull request by ghost**
Changes to display the modal whit dropdown if the option list has over 10 items. 
This issue is already mentioned here: https://github.com/archivematica/Issues/issues/850

### CODE REVIEW

**Comment by sromkey** [comment]
Hi @FransPicturae - thank you for this PR! Have you signed our Contributor's Agreement? If not, you can find it here: https://wiki.archivematica.org/Contributor_Agreement

**Comment by FransPicturae** [comment]
Hi Sarah,
Included the signed Contributor Agreement.



Met vriendelijke groet,


Frans Verbeek

Developer


[Picturae] PICTURAE

J. Duikerweg 14

1703 DH Heerhugowaard

The Netherlands


t:


+31 725 320 444


e:


F.Verbeek@picturae.com


w:


www.picturae.com<https://www.picturae.com/>



LinkedIn<http://www.linkedin.com/company/1237997>


Twitter NL<https://twitter.com/#!/Picturae_NL>


Twitter INT<https://twitter.com/#!/Picturae_INT>


Facebook<http://www.facebook.com/pages/Picturae/358966670821808>


Vele Handen<https://velehanden.nl>

**Review by ross-spencer — COMMENTED** [review]
@FransPicturae I haven't enough experience in the UI to determine an alternative. I am going to suggest this as a suitable bug-fix in the short time, so we'll discuss it for 1.11. I can recreate the old behavior and the old behavior and I can see the improvement. That being said, would you agree the way the modal dialog pops up isn't an entirely satisfactory experience. 

I see a mix of behaviors on Firefox or Chrome, but essentially, everything remains grayed out and I can select from the drop-down either in the top-left corner (Firefox) or the regular drop-down (Chrome) once the grayed out area has disappeared. 

I think aside from the freezing issue there may-be a more holistic fix here, but does that align with your experience? 

(I am using a rebased 1.10 branch btw).

**Comment by ghost** [comment]
@ross-spencer I agree that the way the modal dialog pops up isn't an entirely satisfactory experience. 
Also I also think the solution being `a more holistic fix` is true. I have to explore the code to see if it aligns my experience. I will spent some time in this.

**Comment by replaceafill** [comment]
Hello @FransPicturae :wave: 

> Also I also think the solution being `a more holistic fix` is true. I have to explore the code to see if it aligns my experience. I will spent some time in this.

I was wondering if you had the opportunity to experiment further with this problem. I've created https://github.com/artefactual/archivematica/pull/1578 to address it in a different way, and would like your opinion if you have a chance.

**Comment by ross-spencer** [comment]
Closed by https://github.com/artefactual/archivematica/pull/1578

**Pull request closed without merging**
