### PR TITLE
Fix crash when creating a SIP from a Transfer with UUIDs assigned to directories

### PR DESCRIPTION
**Pull request by jlj5aj**
Please feel free to apply this patch manually instead of merging.  I am not sure this small change merits going through the entire contribution process including the signing of a contributor's agreement.

Connects to https://github.com/archivematica/Issues/issues/192

### CODE REVIEW

**Comment by sromkey** [comment]
Hi @jlj5aj - we're moving ahead to merge this but need you to sign a contributor's agreement (even for a small change, sorry about the hassle!) Thanks! https://github.com/artefactual/archivematica/blob/stable/1.7.x/CONTRIBUTING.md#contributors-agreement

**Comment by jlj5aj** [comment]
Hi @sromkey -- I've emailed my signed contributor's agreement.  Please let me know if there is anything else I need to do.  Thanks!

**Review by sevein — APPROVED** [review]
Thank you! :tada:

**Comment by sevein** [comment]
78d6ed7b in qa/1.x

**Pull request merged**
