### PR TITLE
Allow UTF8-encoded transfer directory names

### PR DESCRIPTION
**Pull request by jrwdunham**

### CODE REVIEW

**Comment by nickwilkinson** [comment]
[UTF8-encoding src and dst in `copy_from_transfer_sources`](https://trello.com/c/9CDk4Ve9/2-utf8-encoding-src-and-dst-in-copyfromtransfersources)

**Review by jhsimpson — COMMENTED** [review]
This looks good, would be nice to add some tests.

**Review by jhsimpson — APPROVED** [review]
:+1:

**Comment by sevein** [comment]
49415a25 in `stable/1.6.x`

**Pull request merged**
