### PR TITLE
MCPClient: use new base Docker image

### PR DESCRIPTION
**Pull request by sevein**
This is connected to https://github.com/archivematica/Issues/issues/527.

### CODE REVIEW

**Comment by sevein** [comment]
@mamedin, I ended up doing it! :dancer:

**Comment by mamedin** [comment]
Hi @sevein , I created a new PR to use bulk-extractor v1.5.5 (latest):

 https://github.com/artefactual-labs/am-packbuild/pull/221/files

**Review by mamedin — APPROVED** [review]
LGTM

**Comment by sevein** [comment]
```
$ docker run --rm -it --entrypoint=bash artefactual/archivematica-mcp-client-base:20190227.01.9a3872e0 -c "dpkg -l bulk-extractor"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  bulk-extractor 1.5.5-1~18.0 amd64        Bulk Extractor (bulk_extractor) i
```

**Pull request merged**
