### PR TITLE
dashboard: handle null sipName ES hit

### PR DESCRIPTION
**Pull request by sevein**

### CODE REVIEW

**Comment by Hwesta** [comment]
Is there any valid case where sipName shouldn't be indexed? It looks like the only time `aips/aipfile` indexes sipName is from `indexAIP.py`, which should always provide the sipName.

**Comment by sevein** [comment]
I saw it happening in that case in production but I couldn't figure out why.

**Comment by Hwesta** [comment]
I'd rather know what's happening, but I'm okay merging it as-is, given that ES isn't a 100% reliable source of data.

:+1:

**Comment by sevein** [comment]
Thank you! e6f83f7e52a2609e0dc9459b48875382c0f21ad0

**Pull request closed without merging**
