### PR TITLE
MCPServer: create reingestAIP directory as part of package install

### PR DESCRIPTION
**Pull request by scollazo**
This fixes the problem with AIP reingest

### CODE REVIEW

**Comment by Hwesta** [comment]
:+1: 

Since this problem should only happen if the shared directory structure already existed, that could probably be moved to inside the if block above.

**Comment by hakamine** [comment]
Do you see any problem if we just do the rsync of the sharedDirectory structure each time there is an upgrade (i.e., remove the "if/then/else" conditionals in the block above ) ? Currently the rsync is not done when the /var/archivematica/sharedDirectory exists, so a similar problem is going to happen when the sharedDirectory structure changes again in the future.

**Comment by scollazo** [comment]
Yes, that won't hurt. But we need to be sure that the sharedDirectory/system/reingest folder is created before the rsync happens, I wasn't able to find it in the git repo.

**Comment by hakamine** [comment]
the reingestAIP folder is inside the structure here  ( watchedDirectories/system/reingestAIP/ ): https://github.com/artefactual/archivematica/tree/stable/1.5.x/src/MCPServer/share/sharedDirectoryStructure

**Comment by jhsimpson** [comment]
:+1:  this looks good to me, and I think it can be merged.

We have analogous code for building rpm's in the am-packbuild repo here:
https://github.com/artefactual-labs/am-packbuild/blob/master/rpm/archivematica/package.spec

I think there needs to be a code change in am-packbuild, to make sure the behaviour when building debs is the same when building rpms, i.e., make sure the sharedDirectory structure is copied over on upgrades not just on installs. 

In a future release of Archivematica, we can move these debian directories from the Archivematica git repo and put them in am-packbuild.

**Comment by scollazo** [comment]
Merged in qa/1.x

**Comment by scollazo** [comment]
Merged into stable/1.5.x too, closing.

**Comment by Hwesta** [comment]
Cherry-picked to qa/1.x as 5ee579c330c601fa88b3927ad078b0411e4c1ea3 and stable/1.5.x as 80c5f2b3c7cd64e608654075a68705f101893563

**Pull request closed without merging**
