### PR TITLE
ArchivesSpace.find_by_field fixes

### PR DESCRIPTION
**Pull request by mistydemeo**
- Fixes returning resource_components, which have a different field name for identifiers.
- Limits the returned types to resources and resource components.

### CODE REVIEW

**Comment by Hwesta** [comment]
:+1:

**Comment by Hwesta** [comment]
Tests? Do tests still pass?

**Comment by mistydemeo** [comment]
Updated tests; they pass now.

**Comment by Hwesta** [comment]
:+1:

**Comment by Hwesta** [comment]
Cherry-picked into qa/1.5.x as 29d1601e5dffaf86787fd79c06a0a7aa1bc54d8f 555997fa2cc917b77e6014aba871d56b723dbf5a abc45b874d81a179a6a1142e1783f72a41ba6035

**Pull request merged**
