### PR TITLE
Dashboard: fix exitmessage values

### LINKED ISSUE #784: Problem: undefined choice set exitmessage in MSCL models
Two fields in our workflow models should have a choice set equivalent to `Job.currentstep`:

- `MicroServiceChainLink.defaultexitmessage`
- `MicroServiceChainLinkExitCode.exitmessage`

Also because this hasn't done before we have mixed values that I think appeared after applying migrations that relied on the default values.

```
mysql> SELECT defaultExitMessage, COUNT(*) FROM MicroServiceChainLinks GROUP BY defaultExitMessage;
+--------------------+----------+
| defaultExitMessage | COUNT(*) |
+--------------------+----------+
| 2                  |        2 |
| 4                  |      320 |
| Failed             |       22 |
+--------------------+----------+
3 rows in set (0.00 sec)
```

```
mysql> SELECT pk, microserviceGroup, defaultExitMessage FROM MicroServiceChainLinks WHERE defaultExitMessage = 'Failed';
+--------------------------------------+--------------------------------------------+--------------------+
| pk                                   | microserviceGroup                          | defaultExitMessage |
+--------------------------------------+--------------------------------------------+--------------------+
| 05357876-a095-4c11-86b5-a7fff01af668 | Bind PIDs                                  | Failed             |
| 0fd20984-db3c-492b-a512-eedd74bacc82 | Policy checks for derivatives              | Failed             |
| 153c5f41-3cfb-47ba-9150-2dd44ebc27df | Policy checks for derivatives              | Failed             |
| 1563f22f-f5f7-4dfe-a926-6ab50d408832 | Include default Transfer processingMCP.xml | Failed             |
| 286bbb36-6a38-41d5-bf7a-a8ba58aa71ce | Normalize                                  | Failed             |
| 3bbfbd27-ba41-4e36-8b7f-b4f02676bda3 | Policy checks for derivatives              | Failed             |
| 5415c813-3637-49ab-afec-9b435c2e4d2c | Approve transfer                           | Failed             |
| 5b0042a2-2244-475c-85d5-41e4b11e65d6 | Normalize                                  | Failed             |
| 6441980c-b64b-447e-abc7-9351a2547f6a | Assign file UUIDs and checksums            | Failed             |
| 6c147aeb-20c5-47ce-9f40-7f22683cea1f | Validation                                 | Failed             |
| 70fc7040-d4fb-4d19-a0e6-792387ca1006 | Validation                                 | Failed             |
| 7677d1cd-2211-4969-8c10-5ec2a93d5c2f | Bind PIDs                                  | Failed             |
| 87e93d08-36e4-4c81-99a8-beea00b18400 | Bind PIDs                                  | Failed             |
| 8882bad4-561c-4126-89c9-f7f0c083d5d7 | Approve transfer                           | Failed             |
| 8ce07e94-6130-4987-96f0-2399ad45c5c2 | Policy checks for derivatives              | Failed             |
| 960f6db0-5b41-417c-bedc-a0eb75a82227 | Include default Transfer processingMCP.xml | Failed             |
| a7c18fee-c8c1-4713-ba74-9705c45efbce | Normalize                                  | Failed             |
| b08ad32b-f94f-4c2a-9fb0-9ef9328718dd | Include default Transfer processingMCP.xml | Failed             |
| bd899573-694e-4d33-8c9b-df0af802437d | Assign file UUIDs and checksums            | Failed             |
| d6f6f5db-4cc2-4652-9283-9ec6a6d181e5 | Include default Transfer processingMCP.xml | Failed             |
| e10a31c3-56df-4986-af7e-2794ddfe8686 | TRIM transfer                              | Failed             |
| f954326a-250b-4666-b2f2-1e54d36958a1 | TRIM transfer                              | Failed             |
+--------------------------------------+--------------------------------------------+--------------------+
```

### PR DESCRIPTION
**Pull request by sevein**
This closes #784.

### CODE REVIEW

**Comment by sevein** [comment]
I had to do a bunch of changes but I haven't tested it yet.

**Review by jrwdunham — COMMENTED** [review]
This looks good to me. I'd like to test it by running a single acceptance test, but it needs to be rebase on qa/1.x before it'll work (crucially needs commit 702db21663c9f2d16ab5106b942d571cf508f850).

**Comment by sevein** [comment]
Ok done. Thanks for doing this. I still have to figure out what's broken in the AT on Docker.

**Comment by sromkey** [comment]
@sevein can this be merged?

**Comment by sevein** [comment]
It was bumped to 1.8, I'll move to the 1.8 project.

**Comment by sevein** [comment]
It needs to be rebased and make sure that this is still relevant.

**Pull request closed without merging**
