### PR TITLE
osdeps updates for 1.8.x

### PR DESCRIPTION
**Pull request by scollazo**
This pr brings 1.8.x repositories and removes packages no longer needed.

Connects to https://github.com/archivematica/Issues/issues/161

### CODE REVIEW

**Comment by scollazo** [comment]
A successful build using this branch can be found at http://jenkins-ci.archivematica.org/job/deploy-pub/job/QA/job/Ubuntu-18.04-QA/3/

**Comment by scollazo** [comment]
Connects to archivematica/Issues#161

**Comment by sevein** [comment]
> Connects to archivematica/Issues#161

@scollazo you need to add the reference in the original description of the pull request otherwise Waffle won't pick up the change.

**Comment by sevein** [comment]
@scollazo should we also remove the init files from this repo like you did in https://github.com/artefactual/archivematica-storage-service/pull/414?

**Comment by scollazo** [comment]
@sevein , init scripts for 14.04 have been removed

**Review by sevein — APPROVED** [review]

**Pull request merged**
