### PR TITLE
Elasticsearch: force str type in some date fields

### PR DESCRIPTION
**Pull request by sevein**
This is a revival of [#8812](https://projects.artefactual.com/issues/8812) / #329 that adds two extra fields with explicit string type.

### CODE REVIEW

**Comment by sevein** [comment]
Merges into `stable/1.4.x`. Should I submit separate pull requests for `qa/1.5.x` and `qa/1.x`?

**Comment by Hwesta** [comment]
> Merges into `stable/1.4.x`. Should I submit separate pull requests for `qa/1.5.x` and `qa/1.x`?

If it cherry picks without issue, it probably doesn't need a new PR, but if it has significant conflicts then a new PR to check it didn't break with newer code is usually a good idea.

**Comment by Hwesta** [comment]
:+1:

**Comment by sevein** [comment]
Ported to `qa/1.5.x` (8cdde5c294add3c619d76926f16544a5b9a9d564) and `qa/1.x` (90b53674bb1fdb6322aadcc46ccbff621b1f4ccb) in #421.

**Pull request closed without merging**
