### PR TITLE
Packaging & mysql seed for 1.5

### PR DESCRIPTION
**Pull request by Hwesta**
- Cherry pick 1.4.x SQL & packaging changes
- Generated mysql seed & update scripts for 1.5

### CODE REVIEW

**Comment by mistydemeo** [comment]
:+1:

**Comment by mistydemeo** [comment]
Can you include 30b43b2cfef3a1a4a01038be9cf5cb27f6391abf? Sorry to change the DB under you.

**Comment by Hwesta** [comment]
This will need to be updated for #387 and #376 once they're merged.

**Comment by Hwesta** [comment]
We're not using mysql migrations anymore - see #409 for Django migrations.

**Pull request closed without merging**
