### PR TITLE
Fixed DIP upload UI JS issue, refs #11213

### PR DESCRIPTION
**Pull request by mcantelon**
Fixed issue preventing DIP upload to AtoM from working.

### CODE REVIEW

**Review by sevein — COMMENTED** [review]
@mcantelon, what was the problem? Has the API changed?

**Review by sevein — CHANGES_REQUESTED** [review]
@mcantelon could you please add some context? I'd like to understand the reason why the code stopped working if it's possible. Has the API of jQuery changed?

**Comment by sevein** [comment]
@mcantelon before merging is it possible to make a comment on the solution please?

**Comment by mcantelon** [comment]
Hi Jesus... sorry, I forgot about this PR. I'll prepare a summary of the issue.

**Comment by sevein** [comment]
Thank you, no problem! You must have the notifications disabled or something like that.

**Comment by mcantelon** [comment]
At the bottom of this jQuery page there's an example similar to the fix in the PR:

https://api.jquery.com/jquery.when/

The "when"-reliant code isn't present in our stable/1.6.x branch so the bug might not have been encountered if noone's tested the qa/1.7.x AtoM DIP uploading functionality since the change was added:

https://github.com/artefactual/archivematica/commits/stable/1.6.x/src/dashboard/src/media/js/ingest.js

**Review by sevein — APPROVED** [review]
Thanks!

**Pull request merged**
