### PR TITLE
Add support for LDAP authentication

### PR DESCRIPTION
**Pull request by helenst**
This adds a new custom auth backend that will authenticate with an LDAP server based on settings (which can be configured in environment variables). This work has been taken from the old MOMA branch and adapted / tidied up.

I've tried to take a similar approach to the way Shibboleth auth is handled, and also brought the Shib and LDAP configurations out into their own modules to reduce clutter in the base config file. It also hooks into some of the `ALLOW_USER_EDITS` stuff that was done in the Shibboleth work, to deal with the generic concept of a remove user.

If this looks OK, a similar PR could be made for storage service.

I tested this out using an LDAP test server: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
which can be configured with the following overrides:
```
AUTH_LDAP_SERVER_URI = 'ldap://ldap.forumsys.com'
AUTH_LDAP_BIND_DN = 'cn=read-only-admin,dc=example,dc=com'
AUTH_LDAP_BIND_PASSWORD = 'password'
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'dc=example,dc=com',
    ldap.SCOPE_SUBTREE,
    '(uid=%(user)s)'
)
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "cn",
    "last_name": "sn",
    'email': 'mail',
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {}
```

and logging in as gauss / password

### CODE REVIEW

**Comment by mcantelon** [comment]
I tried it out and it works like a charm. I didn't see any issues with the code. :+1:

**Comment by sevein** [comment]
@mcantelon, did you mean to close it?

**Comment by mcantelon** [comment]
Oops... didn't mean to close.

**Review by sevein — APPROVED** [review]
@mcantelon approved this above.

**Review by sevein — CHANGES_REQUESTED** [review]
CI check failed. I think it's a minor issue. If you run into issues with the linter that need to be ignored you can do like in here: https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/settings/base.py#L1.

**Comment by helenst** [comment]
Hi @sevein I fixed the linter issue and rebased!

**Pull request merged**
