### PR TITLE
Bring 1.5 changes into qa

### PR DESCRIPTION
**Pull request by Hwesta**
This will merge `stable/1.5.x` into `qa/1.x`, and bring all the changes that only went into 1.5 into mainline. Notably, Django migrations instead of raw SQL migrations (#409). 

Includes #460 #459 #456 #454 #453 #452 #451 #450 #448 #447 #446 #445 #443 #442 #441 #439 #430 #412 #403 #373 #308 

For code review, only the two most recent commits should need it: merge conflict resolution, and adding Django migrations for 1.6-only SQL migrations.

### CODE REVIEW

**Comment by jhsimpson** [comment]
I've had a look at this and it looks to be all in order, at first glance.  Even just focusing on the 2 most recent commits, there are a lot of changes in this PR, so a further look tomorrow is probably wise.

I am going to try deploying from this branch tomorrow, and I'll comment again then.

**Comment by Hwesta** [comment]
Particular areas to check functionality: event identifier UUIDs, checksums on reingest, SIP arrange, DIP store after upload.

**Comment by sromkey** [comment]
Please see:
https://projects.artefactual.com/issues/10142 and
https://projects.artefactual.com/issues/10143

**Comment by sromkey** [comment]
The two issues above have been verified now. Thanks, this is looking good!

**Comment by sevein** [comment]
🎉

**Pull request merged**
