### PR TITLE
When creating one task per file, batch the inserts

### PR DESCRIPTION
**Pull request by marktriggs**
Otherwise tasks end up staggered by the time it takes to perform a DB commit, which in many cases may be longer than the task's execution time.

Yields a small performance improvement, but should also improve the effectiveness of future performance improvements in the MCP Client scripts.

### CODE REVIEW

**Comment by sevein** [comment]
Why do you think that `logTaskCreatedSQL` is so slow?

**Comment by marktriggs** [comment]
It all comes down to the database commits.  The inserts themselves are cheap, but each one runs in its own transaction, auto-committing after each statement.  The commits are slow because they force MySQL to flush to disk--exactly how long that takes depends on the specs of the storage system and how busy it is, but running an ingest against docker on an otherwise unloaded system I see times of around 150ms in general.

Wrapping the inserts in a transaction just batches those inserts into a single disk write, which saves all of that overhead.

Here's a little sample program that shows the difference:

  https://gist.github.com/marktriggs/d68db4a6fe76e39d693151093317839d

running against my Docker setup:

    Time to insert 1000 rows with autocommit = True: 58.905809
    Time to insert 1000 rows with autocommit = False: 0.634376

**Comment by marktriggs** [comment]
Sorry, I also meant to note for posterity that this PR came out of the analysis for https://github.com/artefactual/archivematica/issues/938

**Comment by sevein** [comment]
That's impressive! Do you think that it would be a good alternative to set `AUTOCOMMIT=False` (https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-DATABASE-AUTOCOMMIT) in `src/MCPServer/lib/settings/common.py`? I don't understand how transactions on single statements are beneficial. Originally when the MCPServer was written I think it was using raw SQL queries, later it was updated to use the ORM but for reasons like clarity or reusability of the models.
Also FWIW connections are not shared or recycled. Django's ORM doesn't let you do that. And we also have that decorator in place to make sure that the connections are destroyed when a thread terminates - this was necessary because Django would only do that cleanup after the end of a web request and we don't have those in MCPServer so we have to do it manually. I'm not sure if this is relevant for your work though.

**Comment by marktriggs** [comment]
Yeah, amazing what a difference it makes :)

I don't think turning off autocommit would necessarily be safe... the trouble is, if you don't autocommit then you have to manually do the commits yourself at the right times (and if you miss one, your updates get rolled back), so it's fiddly to retrofit.

I think the main thing is to keep this issue in mind in the interface redesign work we do for https://github.com/artefactual/archivematica/issues/938.  Right now, the architecture of MCP Client makes effective use of transactions quite difficult: if you have 10,000 files that each need a row inserted into the DB, the optimal thing to do is to open a transaction, do your 10,000 inserts, commit the transaction.  But since currently each of those 10,000 files will be processed in a separate thread (with its own DB connection), there's not that opportunity to batch the inserts like that.

Anyway, I'll move the rest of this discussion over to #938 :)

**Comment by sevein** [comment]
@marktriggs, does https://github.com/artefactual/archivematica/pull/1105 deprecate this pull request?

**Comment by marktriggs** [comment]
@sevein Ah, yes!  It does.  Closing this one out :)

**Pull request closed without merging**
