### PR TITLE
Revert "MCPServer: use auto_close_db"

### PR DESCRIPTION
**Pull request by scollazo**
This reverts commit 08ba162a2d609dc8c37b0d1522515a2e9e48fd11.

Fixes archivematica/Issues#52

### CODE REVIEW

**Comment by sevein** [comment]
@scollazo, I've submitted a new PR (https://github.com/artefactual/archivematica/pull/1231) that could  replace yours. I see 08ba162a2d609dc8c37b0d1522515a2e9e48fd11 as necessary. I suspect that the problem you hit is in MCPClient this time - it can be confusing because it's only reproducible when the system has been unused for a long period of time. Let me know what you think.

**Review by sevein — COMMENTED** [review]
Please see https://github.com/artefactual/archivematica/pull/1231.

**Comment by scollazo** [comment]
I found the issue on a new  and clean install. I'll do another clean deploy to be sure that this pr fixes the problem.

**Comment by scollazo** [comment]
Closing in behalf of #1231

**Pull request closed without merging**
