### PR TITLE
Dashboard: fix npm build issues in Dockerfile

### PR DESCRIPTION
**Pull request by sevein**
It completes #678 where the front-end builds were not working in Docker.

To 👍 please test using https://github.com/artefactual-labs/am/tree/master/compose. The branch can be chosen here: https://github.com/artefactual-labs/am/blob/master/playbooks/inc/repos-1.7.yml.

### CODE REVIEW

**Review by jraddaoui — COMMENTED** [review]
Hi @sevein, this is amazing!

I tested it with qa/1.x and with this branch and in both cases I got a 404 error trying to get the builds from the dashboard.

Maybe I'm doing something wrong with docker-compose. After some tries, I think I have been able to fully re-create the containers with:

```
docker-compose stop
docker-compose down
docker-compose build --no-cache
```

I tried with all containers and only with `archivematica-dashboard`

**Comment by sevein** [comment]
Have you checked out the `dev/fix-dashboard-dockerfile-npm` branch in the `src/archivematica` git working directory?

**Comment by jraddaoui** [comment]
Yes, I changed it in the playbooks yml file and used ansible to update the src before recreating the containers.

**Comment by sevein** [comment]
Ok. That's unfortunate. What was the output of the Docker image build when the following lines were executed?

```
RUN chown -R archivematica:archivematica /src/dashboard/frontend/transfer-browser \
    && cd /src/dashboard/frontend/transfer-browser && su -l archivematica -c "npm install"

RUN chown -R archivematica:archivematica /src/dashboard/frontend/appraisal-tab \
    && cd /src/dashboard/frontend/appraisal-tab && su -l archivematica -c "npm install"
```

To be specific, there is a step when you're asked to run `docker-compose build` - or you can rebuild just the Dashboard image with `docker-compose build archivematica-dashboard`. That's where you'll see the output of the commands that we listed in `dashboard.Dockerfile`. I'm assuming that the `npm install` failed and the output will be relevant to solve this issue.

**Comment by jraddaoui** [comment]
It looks like it's trying to build the assets in the archivematica home folder:

```
Step 18/28 : RUN chown -R archivematica:archivematica /src/dashboard/frontend/transfer-browser 	&& cd /src/dashboard/frontend/transfer-browser && su -l archivematica -c "npm install"
 ---> Running in 2494036d59ee
[91mnpm WARN saveError ENOENT: no such file or directory, open '/home/archivematica/package.json'
[0m[91mnpm notice created a lockfile as package-lock.json. You should commit this file.
[0mup to date in 0.053s
[91mnpm WARN enoent ENOENT: no such file or directory, open '/home/archivematica/package.json'
npm WARN archivematica No description
npm WARN archivematica No repository field.
npm WARN archivematica No README data
npm WARN archivematica No license field.

[0m ---> 5a155f4ef5bb
Removing intermediate container 2494036d59ee
Step 19/28 : ADD dashboard/frontend/appraisal-tab/package.json /src/dashboard/frontend/appraisal-tab/package.json
 ---> 4ea50a49a1a9
Removing intermediate container f7dbbcb20171
Step 20/28 : ADD dashboard/frontend/appraisal-tab/package-lock.json /src/dashboard/frontend/appraisal-tab/package-lock.json
 ---> d2c47e3141b5
Removing intermediate container 6232e720a3dd
Step 21/28 : RUN chown -R archivematica:archivematica /src/dashboard/frontend/appraisal-tab 	&& cd /src/dashboard/frontend/appraisal-tab && su -l archivematica -c "npm install"
 ---> Running in 450d256690b0
[91mnpm[0m[91m WARN saveError ENOENT: no such file or directory, open '/home/archivematica/package.json'
[0mup to date in 0.06s
[91mnpm WARN enoent ENOENT: no such file or directory, open '/home/archivematica/package.json'
npm WARN archivematica No description
npm WARN archivematica No repository field.
npm WARN archivematica No README data
npm WARN archivematica No license field.
```

**Comment by sevein** [comment]
@jraddaoui, I think it's fixed now! Please try again.

**Comment by jraddaoui** [comment]
This time it looks like it worked ...

```
Step 15/26 : RUN set -ex 	&& groupadd --gid 333 --system archivematica 	&& useradd --uid 333 --gid 333 --create-home --system archivematica 	&& mkdir -p /src/dashboard/src/media 	&& chown archivematica:archivematica /src/dashboard/src/media
 ---> Running in 44cebf64f62c
[91m+ groupadd --gid 333 --system archivematica
[0m[91m+ useradd --uid 333 --gid 333 --create-home --system archivematica
[0m[91m+ mkdir -p /src/dashboard/src/media
[0m[91m+ chown archivematica:archivematica /src/dashboard/src/media
[0m ---> 76d739d0b225
Removing intermediate container 44cebf64f62c
Step 16/26 : ADD dashboard/frontend/transfer-browser/ /src/dashboard/frontend/transfer-browser/
 ---> cf87183f8d5a
Removing intermediate container 84d29c155d7d
Step 17/26 : RUN chown -R archivematica:archivematica /src/dashboard/frontend/transfer-browser 	&& su -l archivematica -c "cd /src/dashboard/frontend/transfer-browser && npm install"
 ---> Running in 31ca1de32e7e
[91mnpm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
[0m
> transfer-browse@0.0.0 prepublish /src/dashboard/frontend/transfer-browser
> webpack --progress --colors --entry ./app.js

[91m  0% compile[0m[91m 10% 0/1 build modules[0m[91m 70% 1/1 build modules[0m[91m 40% 1/2 build modules 30% 1/3 build modules 25% 1/4 build modules 22% 1/5 build modules 20% 1/6 build modules[0m[91m 18% 1/7 build modules 17% 1/8 build modules[0m[91m 16% 1/9 build modules[0m[91m 16% 1/10 build modules[0m[91m 22% 2/10 build modules[0m[91m 28% 3/10 build modules[0m[91m 34% 4/10 build modules[0m[91m 40% 5/10 build modules[0m[91m 46% 6/10 build modules[0m[91m 42% 6/11 build modules 40% 6/12 build modules 37% 6/13 build modules 35% 6/14 build modules[0m[91m[0m[91m 40% 7/14 build modules 38% 7/15 build modules[0m[91m 36% 7/16 build modules[0m[91m 40% 8/16 build modules 38% 8/17 build modules 36% 8/18 build modules 40% 9/18 build modules[0m[91m 38% 9/19 build modules 37% 9/20 build modules 35% 9/21 build modules[0m[91m 34% 9/22 build modules 33% 9/23 build modules 32% 9/24 build modules 31% 9/25 build modules 34% 10/25 build modules[0m[91m 36% 11/25 build modules 38% 12/25 build modules 41% 13/25 build modules[0m[91m 43% 14/25 build modules 46% 15/25 build modules 48% 16/25 build modules[0m[91m 50% 17/25 build modules[0m[91m 53% 18/25 build modules[0m[91m 55% 19/25 build modules[0m[91m 57% 20/25 build modules 56% 20/26 build modules 54% 20/27 build modules[0m[91m 56% 21/27 build modules[0m[91m 54% 21/28 build modules[0m[91m 57% 22/28 build modules[0m[91m 59% 23/28 build modules 61% 24/28 build modules 59% 24/29 build modules 57% 24/30 build modules[0m[91m[0m[91m 60% 25/30 build modules[0m[91m 58% 25/31 build modules 56% 25/32 build modules[0m[91m 55% 25/33 build modules[0m[91m 57% 26/33 build modules[0m[91m 59% 27/33 build modules[0m[91m 60% 28/33 build modules[0m[91m 62% 29/33 build modules[0m[91m 64% 30/33 build modules 66% 31/33 build modules[0m[91m 68% 32/33 build modules[0m[91m 66% 32/34 build modules[0m[91m 64% 32/35 build modules 63% 32/36 build modules 61% 32/37 build modules 60% 32/38 build modules 59% 32/39 build modules 57% 32/40 build modules 59% 33/40 build modules 58% 33/41 build modules 57% 33/42 build modules 56% 33/43 build modules 54% 33/44 build modules 53% 33/45 build modules 53% 33/46 build modules 52% 33/47 build modules 53% 34/47 build modules 54% 35/47 build modules 55% 36/47 build modules 57% 37/47 build modules[0m[91m 58% 38/47 build modules 59% 39/47 build modules 61% 40/47 build modules 62% 41/47 build modules[0m[91m 63% 42/47 build modules 64% 43/47 build modules 66% 44/47 build modules[0m[91m 67% 45/47 build modules[0m[91m 68% 46/47 build modules 67% 46/48 build modules 66% 46/49 build modules 65% 46/50 build modules 64% 46/51 build modules 63% 46/52 build modules 62% 46/53 build modules 61% 46/54 build modules[0m[91m 62% 47/54 build modules 61% 47/55 build modules 62% 48/55 build modules 63% 49/55 build modules 64% 50/55 build modules 65% 51/55 build modules 66% 52/55 build modules 67% 53/55 build modules 68% 54/55 build modules[0m[91m 70% 55/55 build modules 68% 55/56 build modules 67% 55/57 build modules 66% 55/58 build modules 65% 55/59 build modules 64% 55/60 build modules 64% 55/61 build modules 63% 55/62 build modules 62% 55/63 build modules 61% 55/64 build modules 60% 55/65 build modules 60% 55/66 build modules 59% 55/67 build modules 58% 55/68 build modules 57% 55/69 build modules 57% 55/70 build modules 57% 56/70 build modules 58% 57/70 build modules 59% 58/70 build modules 60% 59/70 build modules 61% 60/70 build modules 62% 61/70 build modules 63% 62/70 build modules[0m[91m 64% 63/70 build modules 64% 64/70 build modules 65% 65/70 build modules 66% 66/70 build modules[0m[91m 67% 67/70 build modules[0m[91m 68% 68/70 build modules[0m[91m 69% 69/70 build modules 70% 70/70 build modules 69% 70/71 build modules 68% 70/72 build modules 67% 70/73 build modules 66% 70/74 build modules 65% 70/75 build modules 65% 70/76 build modules 64% 70/77 build modules 63% 70/78 build modules 63% 70/79 build modules 62% 70/80 build modules 61% 70/81 build modules 61% 70/82 build modules 60% 70/83 build modules 60% 70/84 build modules 59% 70/85 build modules 58% 70/86 build modules 58% 70/87 build modules 57% 70/88 build modules 57% 70/89 build modules 56% 70/90 build modules 56% 70/91 build modules 55% 70/92 build modules 55% 70/93 build modules 54% 70/94 build modules 54% 70/95 build modules 54% 71/95 build modules 55% 72/95 build modules 56% 73/95 build modules 56% 74/95 build modules 57% 75/95 build modules 57% 76/95 build modules 58% 77/95 build modules 59% 78/95 build modules 59% 79/95 build modules 60% 80/95 build modules 61% 81/95 build modules 61% 82/95 build modules 62% 83/95 build modules 63% 84/95 build modules 63% 85/95 build modules 64% 86/95 build modules 64% 87/95 build modules 65% 88/95 build modules 66% 89/95 build modules 66% 90/95 build modules 67% 91/95 build modules 68% 92/95 build modules 68% 93/95 build modules 69% 94/95 build modules 70% 95/95 build modules 69% 95/96 build modules 68% 95/97 build modules 68% 95/98 build modules 67% 95/99 build modules 67% 95/100 build modules 66% 95/101 build modules[0m[91m 67% 96/101 build modules 67% 97/101 build modules 68% 98/101 build modules 68% 99/101 build modules 69% 100/101 build modules 70% 101/101 build modules 69% 101/102 build modules 68% 101/103 build modules 68% 101/104 build modules 68% 102/104 build modules 69% 103/104 build modules 70% 104/104 build modules 69% 104/105 build modules 68% 104/106 build modules 69% 105/106 build modules 70% 106/106 build modules                  71% seal[0m[91m 73% optimize[0m[91m  75% hashing[0m[91m 76% create chunk assets[0m[91m 78% additional chunk assets   80% optimize chunk assets       90% optimize assets            95% emit[0m[91m         [0mHash: [1mabc9ef63a2a45851be74[22m
Version: webpack [1m1.15.0[22m
Time: [1m1953[22mms
              [1mAsset[22m     [1mSize[22m  [1mChunks[22m  [1m[22m           [1mChunk Names[22m
[1m[32mtransfer_browser.js[39m[22m  2.48 MB       [1m0[22m  [1m[32m[emitted][39m[22m  null
    + 106 hidden modules
added 564 packages in 25.711s
 ---> 97002b89aaf6
Removing intermediate container 31ca1de32e7e
Step 18/26 : ADD dashboard/frontend/appraisal-tab/ /src/dashboard/frontend/appraisal-tab/
 ---> 94f04e7c5902
Removing intermediate container e235bd33be56
Step 19/26 : RUN chown -R archivematica:archivematica /src/dashboard/frontend/appraisal-tab 	&& su -l archivematica -c "cd /src/dashboard/frontend/appraisal-tab && npm install"
 ---> Running in a3d3d1aa79e5
[91mnpm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
[0m
> appraisal-tab@0.0.0 prepublish /src/dashboard/frontend/appraisal-tab
> webpack --progress --colors --entry ./app.js

[91m  0% compile[0m[91m 10% 0/1 build modules[0m[91m 70% 1/1 build modules[0m[91m 40% 1/2 build modules 30% 1/3 build modules 25% 1/4 build modules 22% 1/5 build modules 20% 1/6 build modules 18% 1/7 build modules 17% 1/8 build modules 16% 1/9 build modules 16% 1/10 build modules 15% 1/11 build modules 15% 1/12 build modules 14% 1/13 build modules 14% 1/14 build modules 14% 1/15 build modules 13% 1/16 build modules 13% 1/17 build modules 13% 1/18 build modules 13% 1/19 build modules 13% 1/20 build modules 12% 1/21 build modules 12% 1/22 build modules 12% 1/23 build modules 12% 1/24 build modules 12% 1/25 build modules 12% 1/26 build modules[0m[91m 12% 1/27 build modules 12% 1/28 build modules 12% 1/29 build modules 12% 1/30 build modules[0m[91m 11% 1/31 build modules[0m[91m 11% 1/32 build modules 11% 1/33 build modules 11% 1/34 build modules 11% 1/35 build modules 11% 1/36 build modules 11% 1/37 build modules 11% 1/38 build modules 11% 1/39 build modules 11% 1/40 build modules 11% 1/41 build modules 11% 1/42 build modules 11% 1/43 build modules 11% 1/44 build modules[0m[91m 11% 1/45 build modules 11% 1/46 build modules[0m[91m 11% 1/47 build modules 11% 1/48 build modules 11% 1/49 build modules[0m[91m 12% 2/49 build modules[0m[91m 13% 3/49 build modules[0m[91m 14% 4/49 build modules[0m[91m 16% 5/49 build modules[0m[91m 17% 6/49 build modules[0m[91m 18% 7/49 build modules[0m[91m 19% 8/49 build modules[0m[91m 21% 9/49 build modules[0m[91m 22% 10/49 build modules[0m[91m 23% 11/49 build modules[0m[91m 24% 12/49 build modules[0m[91m 25% 13/49 build modules[0m[91m 27% 14/49 build modules[0m[91m 28% 15/49 build modules[0m[91m 29% 16/49 build modules[0m[91m 30% 17/49 build modules[0m[91m 32% 18/49 build modules[0m[91m 33% 19/49 build modules[0m[91m 34% 20/49 build modules[0m[91m 35% 21/49 build modules[0m[91m 36% 22/49 build modules[0m[91m 38% 23/49 build modules[0m[91m 39% 24/49 build modules[0m[91m 40% 25/49 build modules[0m[91m 41% 26/49 build modules[0m[91m 41% 26/50 build modules 40% 26/51 build modules 40% 26/52 build modules 39% 26/53 build modules[0m[91m 40% 27/53 build modules 40% 27/54 build modules[0m[91m 39% 27/55 build modules[0m[91m 40% 28/55 build modules 40% 28/56 build modules 39% 28/57 build modules 40% 29/57 build modules 40% 29/58 build modules[0m[91m 41% 30/58 build modules[0m[91m 40% 30/59 build modules 40% 30/60 build modules 39% 30/61 build modules 39% 30/62 build modules[0m[91m 40% 31/62 build modules[0m[91m 40% 32/62 build modules 41% 33/62 build modules[0m[91m 41% 33/63 build modules 40% 33/64 build modules 40% 33/65 build modules 40% 33/66 build modules[0m[91m 40% 34/66 build modules[0m[91m 41% 35/66 build modules[0m[91m 42% 36/66 build modules 43% 37/66 build modules[0m[91m 44% 38/66 build modules[0m[91m 45% 39/66 build modules[0m[91m 46% 40/66 build modules 47% 41/66 build modules 48% 42/66 build modules 49% 43/66 build modules[0m[91m 50% 44/66 build modules 50% 45/66 build modules 51% 46/66 build modules[0m[91m 52% 47/66 build modules 53% 48/66 build modules 52% 48/67 build modules 53% 49/67 build modules 54% 50/67 build modules 55% 51/67 build modules 56% 52/67 build modules[0m[91m 57% 53/67 build modules 58% 54/67 build modules 59% 55/67 build modules[0m[91m 60% 56/67 build modules[0m[91m 61% 57/67 build modules[0m[91m 61% 58/67 build modules[0m[91m 62% 59/67 build modules 62% 59/68 build modules[0m[91m 62% 60/68 build modules[0m[91m 63% 61/68 build modules[0m[91m 64% 62/68 build modules[0m[91m 63% 62/69 build modules 63% 62/70 build modules 62% 62/71 build modules 63% 63/71 build modules 64% 64/71 build modules[0m[91m 64% 65/71 build modules 64% 65/72 build modules 63% 65/73 build modules[0m[91m 64% 66/73 build modules[0m[91m 63% 66/74 build modules[0m[91m 64% 67/74 build modules 63% 67/75 build modules 62% 67/76 build modules 62% 67/77 build modules[0m[91m 61% 67/78 build modules[0m[91m 62% 68/78 build modules[0m[91m 63% 69/78 build modules[0m[91m 63% 70/78 build modules[0m[91m[0m[91m 64% 71/78 build modules[0m[91m 65% 72/78 build modules[0m[91m 64% 72/79 build modules 64% 72/80 build modules 63% 72/81 build modules 62% 72/82 build modules 62% 72/83 build modules 61% 72/84 build modules 60% 72/85 build modules 60% 72/86 build modules 59% 72/87 build modules 59% 72/88 build modules 58% 72/89 build modules 57% 72/90 build modules 57% 72/91 build modules 56% 72/92 build modules 56% 72/93 build modules[0m[91m 55% 72/94 build modules[0m[91m 55% 72/95 build modules 54% 72/96 build modules 54% 72/97 build modules 54% 72/98 build modules 53% 72/99 build modules 53% 72/100 build modules 52% 72/101 build modules 52% 72/102 build modules 51% 72/103 build modules 51% 72/104 build modules 51% 72/105 build modules 50% 72/106 build modules 50% 72/107 build modules 50% 72/108 build modules 49% 72/109 build modules 49% 72/110 build modules 48% 72/111 build modules 48% 72/112 build modules 48% 72/113 build modules 47% 72/114 build modules 47% 72/115 build modules 47% 72/116 build modules 46% 72/117 build modules 46% 72/118 build modules 46% 72/119 build modules 46% 72/120 build modules 45% 72/121 build modules 45% 72/122 build modules 45% 72/123 build modules 44% 72/124 build modules 44% 72/125 build modules 44% 72/126 build modules 44% 72/127 build modules 43% 72/128 build modules 43% 72/129 build modules 43% 72/130 build modules 42% 72/131 build modules 42% 72/132 build modules 42% 72/133 build modules 42% 72/134 build modules 42% 72/135 build modules 41% 72/136 build modules 41% 72/137 build modules 41% 72/138 build modules 41% 72/139 build modules 40% 72/140 build modules 40% 72/141 build modules 40% 72/142 build modules 40% 72/143 build modules 40% 72/144 build modules 39% 72/145 build modules[0m[91m 39% 72/146 build modules 39% 72/147 build modules 39% 72/148 build modules 38% 72/149 build modules 38% 72/150 build modules 38% 72/151 build modules 38% 72/152 build modules 38% 72/153 build modules 38% 72/154 build modules 37% 72/155 build modules 37% 72/156 build modules 37% 72/157 build modules 37% 72/158 build modules 37% 72/159 build modules 37% 72/160 build modules 36% 72/161 build modules 36% 72/162 build modules 36% 72/163 build modules 36% 72/164 build modules 36% 72/165 build modules 36% 72/166 build modules 35% 72/167 build modules 35% 72/168 build modules 35% 72/169 build modules 35% 72/170 build modules 35% 72/171 build modules 35% 72/172 build modules 34% 72/173 build modules 34% 72/174 build modules 34% 72/175 build modules 34% 72/176 build modules 34% 72/177 build modules 34% 72/178 build modules 34% 72/179 build modules 34% 72/180 build modules 33% 72/181 build modules 33% 72/182 build modules 33% 72/183 build modules 33% 72/184 build modules 33% 72/185 build modules 33% 72/186 build modules 33% 72/187 build modules 32% 72/188 build modules 32% 72/189 build modules 32% 72/190 build modules 32% 72/191 build modules 32% 72/192 build modules 32% 72/193 build modules 32% 73/193 build modules 33% 74/193 build modules 32% 74/194 build modules[0m[91m 33% 75/194 build modules 33% 76/194 build modules 33% 77/194 build modules[0m[91m 33% 77/195 build modules[0m[91m 33% 77/196 build modules 33% 77/197 build modules 33% 77/198 build modules 33% 77/199 build modules 33% 77/200 build modules 32% 77/201 build modules[0m[91m 33% 78/201 build modules 33% 78/202 build modules 33% 78/203 build modules 32% 78/204 build modules 32% 78/205 build modules 32% 78/206 build modules[0m[91m 33% 79/206 build modules 33% 80/206 build modules 33% 81/206 build modules 33% 82/206 build modules 34% 83/206 build modules 34% 84/206 build modules 34% 85/206 build modules 35% 86/206 build modules 35% 87/206 build modules[0m[91m 35% 88/206 build modules 35% 89/206 build modules 36% 90/206 build modules 36% 91/206 build modules 36% 92/206 build modules 37% 93/206 build modules 37% 94/206 build modules[0m[91m 37% 95/206 build modules 37% 96/206 build modules 38% 97/206 build modules 38% 98/206 build modules[0m[91m 38% 99/206 build modules 39% 100/206 build modules 39% 101/206 build modules 39% 102/206 build modules 40% 103/206 build modules 40% 104/206 build modules 40% 105/206 build modules 40% 106/206 build modules 41% 107/206 build modules 41% 108/206 build modules 41% 109/206 build modules 42% 110/206 build modules 42% 111/206 build modules 42% 112/206 build modules 42% 113/206 build modules 43% 114/206 build modules 43% 115/206 build modules 43% 116/206 build modules 44% 117/206 build modules 44% 118/206 build modules 44% 119/206 build modules 44% 120/206 build modules 45% 121/206 build modules 45% 122/206 build modules 45% 123/206 build modules 46% 124/206 build modules 46% 125/206 build modules 46% 126/206 build modules 46% 127/206 build modules 47% 128/206 build modules 47% 129/206 build modules 47% 130/206 build modules 48% 131/206 build modules 48% 132/206 build modules 48% 133/206 build modules 49% 134/206 build modules 49% 135/206 build modules 49% 136/206 build modules 49% 137/206 build modules 50% 138/206 build modules 50% 139/206 build modules[0m[91m 50% 140/206 build modules 51% 141/206 build modules 51% 142/206 build modules 51% 143/206 build modules[0m[91m 51% 144/206 build modules 52% 145/206 build modules[0m[91m 52% 146/206 build modules 52% 147/206 build modules 53% 148/206 build modules 53% 149/206 build modules 53% 150/206 build modules 53% 151/206 build modules 54% 152/206 build modules 54% 153/206 build modules 54% 154/206 build modules 55% 155/206 build modules 55% 156/206 build modules 55% 157/206 build modules 56% 158/206 build modules 56% 159/206 build modules 56% 160/206 build modules 56% 161/206 build modules 57% 162/206 build modules 57% 163/206 build modules 57% 164/206 build modules 58% 165/206 build modules 58% 166/206 build modules 58% 167/206 build modules 58% 168/206 build modules 59% 169/206 build modules 59% 170/206 build modules 59% 171/206 build modules 60% 172/206 build modules 60% 173/206 build modules 60% 174/206 build modules 60% 175/206 build modules 61% 176/206 build modules 61% 177/206 build modules 61% 178/206 build modules 62% 179/206 build modules 62% 180/206 build modules 62% 181/206 build modules 63% 182/206 build modules 63% 183/206 build modules 63% 184/206 build modules 63% 185/206 build modules 64% 186/206 build modules 64% 187/206 build modules 64% 188/206 build modules 65% 189/206 build modules 65% 190/206 build modules 65% 191/206 build modules 65% 192/206 build modules 66% 193/206 build modules 65% 193/207 build modules[0m[91m 66% 194/207 build modules 66% 195/207 build modules 66% 196/207 build modules 67% 197/207 build modules 67% 198/207 build modules 67% 199/207 build modules[0m[91m 67% 200/207 build modules 68% 201/207 build modules 68% 202/207 build modules 68% 203/207 build modules 69% 204/207 build modules 69% 205/207 build modules[0m[91m 69% 206/207 build modules[0m[91m 70% 207/207 build modules 69% 207/208 build modules 69% 207/209 build modules 69% 207/210 build modules 68% 207/211 build modules 68% 207/212 build modules 68% 207/213 build modules 68% 207/214 build modules 67% 207/215 build modules 68% 208/215 build modules 68% 209/215 build modules 68% 210/215 build modules 68% 211/215 build modules 69% 212/215 build modules 69% 213/215 build modules 69% 214/215 build modules[0m[91m 70% 215/215 build modules 69% 215/216 build modules 69% 215/217 build modules 69% 215/218 build modules 68% 215/219 build modules 68% 215/220 build modules 68% 215/221 build modules 68% 215/222 build modules 67% 215/223 build modules 67% 215/224 build modules 67% 215/225 build modules 67% 215/226 build modules 66% 215/227 build modules 66% 215/228 build modules 66% 215/229 build modules 66% 215/230 build modules 65% 215/231 build modules 66% 216/231 build modules 66% 217/231 build modules 66% 218/231 build modules 66% 219/231 build modules 67% 220/231 build modules 67% 221/231 build modules[0m[91m 67% 222/231 build modules[0m[91m 67% 223/231 build modules[0m[91m 68% 224/231 build modules 68% 225/231 build modules 68% 226/231 build modules 68% 227/231 build modules 69% 228/231 build modules 69% 229/231 build modules 69% 230/231 build modules[0m[91m 70% 231/231 build modules 69% 231/232 build modules 69% 231/233 build modules 69% 231/234 build modules 68% 231/235 build modules 68% 231/236 build modules 68% 231/237 build modules 68% 231/238 build modules 67% 231/239 build modules 67% 231/240 build modules 67% 231/241 build modules 67% 231/242 build modules 67% 231/243 build modules 66% 231/244 build modules 66% 231/245 build modules 66% 231/246 build modules 66% 231/247 build modules 65% 231/248 build modules 65% 231/249 build modules 65% 231/250 build modules 65% 231/251 build modules 64% 231/252 build modules 64% 231/253 build modules 64% 231/254 build modules[0m[91m 64% 231/255 build modules 64% 231/256 build modules 64% 232/256 build modules 64% 233/256 build modules 64% 234/256 build modules 65% 235/256 build modules 65% 236/256 build modules 65% 237/256 build modules 65% 238/256 build modules 66% 239/256 build modules 66% 240/256 build modules 66% 241/256 build modules 66% 242/256 build modules 66% 243/256 build modules 67% 244/256 build modules 67% 245/256 build modules 67% 246/256 build modules 67% 247/256 build modules 68% 248/256 build modules 68% 249/256 build modules 68% 250/256 build modules 68% 251/256 build modules 69% 252/256 build modules 69% 253/256 build modules 69% 254/256 build modules 69% 255/256 build modules 70% 256/256 build modules 69% 256/257 build modules 69% 256/258 build modules 69% 256/259 build modules 69% 256/260 build modules 68% 256/261 build modules 68% 256/262 build modules 68% 257/262 build modules 69% 258/262 build modules 69% 259/262 build modules 69% 260/262 build modules 69% 261/262 build modules 70% 262/262 build modules 69% 262/263 build modules 69% 262/264 build modules 69% 262/265 build modules 69% 262/266 build modules 68% 262/267 build modules 69% 263/267 build modules 69% 264/267 build modules 69% 265/267 build modules 69% 266/267 build modules 70% 267/267 build modules                  71% seal[0m[91m 73% optimize[0m[91m  75% hashing[0m[91m 76% create chunk assets[0m[91m 78% additional chunk assets   80% optimize chunk assets       90% optimize assets            95% emit[0m[91m         [0mHash: [1mffe654633b61352266c4[22m
Version: webpack [1m1.15.0[22m
Time: [1m3759[22mms
           [1mAsset[22m     [1mSize[22m  [1mChunks[22m  [1m[22m           [1mChunk Names[22m
[1m[32mappraisal_tab.js[39m[22m  3.12 MB       [1m0[22m  [1m[32m[emitted][39m[22m  null
    + 267 hidden modules
added 559 packages in 13.551s
 ---> a71eab2c6413
Removing intermediate container a3d3d1aa79e5
```

But I'm getting the same 404 errors. I can't see the "node_modules" folders or the builds created in the src folder and, if I create the assets manually, the errors are removed.

**Comment by sevein** [comment]
I gave it another try and and I think I've found the problem. When the Docker image is built the assets are compiled successfully (thanks to this PR) and included in the final artifact (for production) but later Compose mounts your local `src/archivematica` where the assets haven't been compiled yet. I've updated the `Makefile` in am.git accordingly (https://github.com/artefactual-labs/am/commit/2998d44e94571ddf21d368e9544f539231516d53). If you `git pull --rebase` there and run `make bootstrap-dashboard-frontend` you should for once see the frontend apps working.

To be clear, this PR is still relevant and should be merged. If you confirm it's working, merge please!

**Comment by jraddaoui** [comment]
Great, thanks @sevein!

But I'm having permission issues:

```
$ make bootstrap-dashboard-frontend
docker-compose run --rm --no-deps \
		--entrypoint npm \
		--workdir /src/dashboard/frontend/transfer-browser \
			archivematica-dashboard \
				install
npm WARN checkPermissions Missing write access to /src/dashboard/frontend/transfer-browser
npm ERR! path /src/dashboard/frontend/transfer-browser
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/src/dashboard/frontend/transfer-browser'
npm ERR!  { Error: EACCES: permission denied, access '/src/dashboard/frontend/transfer-browser'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/src/dashboard/frontend/transfer-browser\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/src/dashboard/frontend/transfer-browser' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/archivematica/.npm/_logs/2017-09-09T10_53_21_022Z-debug.log
make: *** [bootstrap-dashboard-frontend] Error 243
```

**Comment by jraddaoui** [comment]
It looks like Compose mounts the files as root by default. Using the following code in https://github.com/artefactual-labs/am/blob/master/compose/Makefile for the "bootstrap-dashboard-frontend" task worked for me:

```
bootstrap-dashboard-frontend:
	docker-compose run --rm --no-deps \
		--user root \
		--entrypoint npm \
		--workdir /src/dashboard/frontend/transfer-browser \
			archivematica-dashboard \
				install --unsafe-perm
	docker-compose run --rm --no-deps \
		--user root \
		--entrypoint npm \
		--workdir /src/dashboard/frontend/appraisal-tab \
			archivematica-dashboard \
				install --unsafe-perm
```

But I'm not sure if it's the best option, so I'll leave that up to you ;)

**Comment by sevein** [comment]
Ok, I've committed your solution. I'm not sure what's going on but we can figure it out later.

**Pull request merged**
