### PR TITLE
Automated workflow and default location

### PR DESCRIPTION
**Pull request by helenst**
Another attempt following on from #698

Now based against the qa/1.x branch and including policy check configurations for both automated and default workflows.

I have been testing this with https://github.com/artefactual/archivematica-storage-service/pull/212 and it seems fine. (I am getting store DIP failures but I also get those on qa/1.x)

### CODE REVIEW

**Comment by sevein** [comment]
Refs #667 #669

**Review by sevein — CHANGES_REQUESTED** [review]
@helenst small comment, I think we're also missing entries in the processing configuration for `Store DIP location` right?

I would recommend to modify the `automated` workflow from the Dashboard (admin > processing config). Once you do that the new document should be available at `/var/archivematica/sharedDirectory/sharedMicroServiceTasksConfigs/processingMCPConfigs/automatedProcessingMCP.xml`. You can copy that again into `src/MCPServer/lib/archivematicaMCP.py`.

image

I was going to make the edits myself but I don't have access to your repo :) I got too used to put my hands in topic branches that don't belong to me but that's probably not great.

**Review by jrwdunham — APPROVED** [review]
👍 lgtm

**Comment by sevein** [comment]
I merged. I'll do the suggested changes in a separate PR.

**Pull request merged**
