### PR TITLE
WIP: Replace hashdeep with coreutils hash utilities

### PR DESCRIPTION
**Pull request by ross-spencer**
:construction: :construction: :construction: :construction: :construction: :construction: 

Work to replace hashdeep in Archivematica. 

TODO:

* Push the docker-base image (currently a test one is on the server)
* Change the script name and module name (merge post i18n)
* Documentation about other hashes if we want them, e.g. including sha512
* Documentation that describes more specific requirements for the hash files supplied with Archivematica, i.e. current demo-transfer won't work with its current configuration.

Open questions:

* Do we still want the log output from the shell script ?
* It is easy  now to add other hashing algorithms, do we want to add sha512sum?
* What would automated testing look like?

Connected to archivematica/Issues#346
Connected to artefactual/archivematica#1061

Output currently looks as followss in the UI"

image

image

And in the PREMIS:
```
<premis:event xmlns:premis="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
  <premis:eventIdentifier>
    <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
    <premis:eventIdentifierValue>7be84e31-6f2c-41e6-966a-a7995a58470a</premis:eventIdentifierValue>
  </premis:eventIdentifier>
  <premis:eventType>fixity check</premis:eventType>
  <premis:eventDateTime>2018-12-30T17:04:06.276741+00:00</premis:eventDateTime>
  <premis:eventDetail>sha1sum (GNU coreutils) 8.28</premis:eventDetail>
  <premis:eventOutcomeInformation>
    <premis:eventOutcome>Pass</premis:eventOutcome>
    <premis:eventOutcomeDetail>
      <premis:eventOutcomeDetailNote></premis:eventOutcomeDetailNote>
    </premis:eventOutcomeDetail>
  </premis:eventOutcomeInformation>
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>Archivematica-1.9</premis:linkingAgentIdentifierValue>
  </premis:linkingAgentIdentifier>
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
  </premis:linkingAgentIdentifier>
</premis:event>
```
```
<premis:event xmlns:premis="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
  <premis:eventIdentifier>
    <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
    <premis:eventIdentifierValue>efebb151-33ad-430d-894c-e7d9851d6642</premis:eventIdentifierValue>
  </premis:eventIdentifier>
  <premis:eventType>fixity check</premis:eventType>
  <premis:eventDateTime>2018-12-30T17:04:05.205950+00:00</premis:eventDateTime>
  <premis:eventDetail>sha512sum (GNU coreutils) 8.28</premis:eventDetail>
  <premis:eventOutcomeInformation>
    <premis:eventOutcome>Pass</premis:eventOutcome>
    <premis:eventOutcomeDetail>
      <premis:eventOutcomeDetailNote></premis:eventOutcomeDetailNote>
    </premis:eventOutcomeDetail>
  </premis:eventOutcomeInformation>
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>Archivematica-1.9</premis:linkingAgentIdentifierValue>
  </premis:linkingAgentIdentifier>
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
  </premis:linkingAgentIdentifier>
</premis:event>
```

### CODE REVIEW

**Comment by sevein** [comment]
@ross-spencer, wouldn't be a better option to implement the script in Python? It wouldn't need ack installed and we could easily write a bunch of new tests.

**Comment by ross-spencer** [comment]
Hi @sevein, between the two I could see:

* Bash: Speed of developing like-for-like and building on what was there (not starting from scratch) and trying a suggested approach from the original ticket.
* Python: Additional automated testing but writing something new; also, with some consideration, not necessarily using a Linux command at all. 

With 99% of this ready, I think it would be good to answer some of the open questions and then review this with the hope of merging and then discuss what a next-step for a future iteration might be. 

Would that be okay?

**Comment by sevein** [comment]
I understand, but how are the tests going to look like? Which testing framework are you going to use? bats? Are you going to wire it into Compose and Travis? I suspect that's going to take a significant amount of time, testing always does - much more than 1% of the total effort.

I don't even feel qualified to evaluate the correctness of your code, but I can try if you insist. I don't think I understand escaping and quoting in bash properly. This is why I find the Python option very compelling. And there's more in Python that you haven't mentioned, e.g. MCPClient can run Python code inline and we wouldn't need to run a new Python interpreter each time you run `createEventsForGroup.py`. We could even get rid of the latter since it's only used by `verifyMD5.sh`. It would use application-level logging and it could leverage future improvements like database connection pooling.

**Comment by ross-spencer** [comment]
Replaced by https://github.com/artefactual/archivematica/pull/1333

**Pull request closed without merging**
