### PR TITLE
Reduce DB queries

### PR DESCRIPTION
**Pull request by Hwesta**
Convert several places that fetch and object, update and save it to use filter, which generates better SQL.

Try to ensure that unitFile replacement dicts only query the parent object once.  Unsure why this required changes in ReplacementDict for unicode.

### CODE REVIEW

**Comment by mistydemeo** [comment]
:+1:

**Comment by Hwesta** [comment]
Update to Django 1.6 to use [CONN_MAX_AGE](https://docs.djangoproject.com/en/1.6/ref/databases/#persistent-connections)

**Comment by mistydemeo** [comment]
Do the changes you made to Units to query for the model only once still have the issue with caching you'd encountered previously? e.g., that they could end up not reflecting changes made by MCPClient?

**Comment by Hwesta** [comment]
Rebased on top of #124.  Need to re-add and re-test changes around CONN_MAX_AGE

**Pull request closed without merging**
