### PR TITLE
Dev/issue 8995 store after upload

### PR DESCRIPTION
**Pull request by mcantelon**
- add new chain/links for post-upload DIP storage
- modify AtoM and ATK upload links to continue to new chain
- add ability to select default post-upload DIP storage destination location

### CODE REVIEW

**Comment by Hwesta** [comment]
We already have a chain to upload DIPS (starting with MicroServiceChainLink `ed5d8475-3793-4fb0-a8df-94bd79b26a4c`); this should set the last MSCL of the 3 upload chains point to `ed5d`, instead adding new MSCLs.  Then we wouldn't need to duplicate the all the MicroServiceChainLinks (and associated entries).  Don't forget to update both `MicroServiceChainLinksExitCodes.nextMicroServiceChainLink` and `MicroServiceChainLinks.defaultNextChainLink`

If you haven't found it already, [graph-links in AM-devtools](https://github.com/artefactual/archivematica-devtools/blob/master/tools/graph-links) is very useful for seeing the existing workflows and deciding on modifications.  There's even some new docs for it at artefactual/archivematica-devtools#8

**Comment by mcantelon** [comment]
This chain isn't to upload DIPs, it's to store them after they're uploaded. There is already a chain to store DIPs that haven't been uploaded, but this new chain is slightly different as a "move" link has to be different (given the DIP, after upload, gets moved to a different directory).

**Comment by Hwesta** [comment]
Oops, I mistyped - I meant store DIPs instead of upload DIPs in the first sentence.

Currently, last node in the 'Upload DIP to AtoM', 'Upload DIP to CONTENTdm' and 'Upload DIP to Archivist's Toolkit' is `e3ef` 'Move to the uploadedDIPs directory'.  I'm suggesting changing the link to point to the already existing chain starting with `ed5d` 'Retrieve DIP Storage Locations'.  This mean that we won't have duplicate nodes doing the same thing and it's a much smaller change.

E.g.

``` sql
SET @upload_atom_tail = '651236d2-d77f-4ca7-bfe9-6332e96608ff' COLLATE utf8_unicode_ci;
SET @upload_cdm_tail = 'f12ece2c-fb7e-44de-ba87-7e3c5b6feb74' COLLATE utf8_unicode_ci;
SET @upload_atk_tail = 'bb1f1ed8-6c92-46b9-bab6-3a37ffb665f1' COLLATE utf8_unicode_ci;
SET @store_start = 'ed5d8475-3793-4fb0-a8df-94bd79b26a4c' COLLATE utf8_unicode_ci;

UPDATE MicroServiceChainLinks SET defaultNextChainLink=@store_start WHERE pk IN (@upload_atom_tail, @upload_cdm_tail, @upload_atk_tail);
UPDATE MicroServiceChainLinksExitCodes SET nextmicroservicechainlink = @store_start where microServiceChainLink IN (@upload_atom_tail, @upload_cdm_tail, @upload_atk_tail);
```

Would it be helpful to discuss this in person?

**Comment by mcantelon** [comment]
Hrm, seems like your fix works! I could have sworn I tried that originally, but I must have done something different. Anyways, thanks! I'll update the PR with this.

**Comment by mistydemeo** [comment]
What's the new behaviour I should be seeing? I set up a server using this, but the DIP upload/store behaviour seems to be the same.

**Pull request closed without merging**
