### PR TITLE
Add new FPR formats, commands and tools

### PR DESCRIPTION
**Pull request by mistydemeo**
- Batch import of all PRONOM formats, as of PRONOM v74
- Add ffprobe, mediainfo, exiftool FPTools, commands and
  characterization rules

### CODE REVIEW

**Comment by Hwesta** [comment]
We need to escape double quotes in FPCommands?  Isn't that handled by being inside single quotes?

**Comment by Hwesta** [comment]
Too much SQL to review properly... it's probably fine.

**Comment by mistydemeo** [comment]
> We need to escape double quotes in FPCommands? Isn't that handled by being inside single quotes?

Probably it is! This SQL was generated by Django, and I didn't alter it in any way - not sure if this is just Django being overcareful, or if it's actually necessary.

**Comment by Hwesta** [comment]
Fair - let's assume Django isn't inserting spurious "s.

**Pull request merged**
