### PR TITLE
Fixes for verifyMD5

### PR DESCRIPTION
**Pull request by mistydemeo**
- Hardcode "checksum" as the filename; this was technically customizeable, but it was never used, and that feature was broken.
- Fix the `groupType` passed to the Django ORM

### CODE REVIEW

**Comment by mistydemeo** [comment]
Updated to change the database and remove the unused variable entirely.

**Comment by Hwesta** [comment]
:+1:

**Comment by jhsimpson** [comment]
:+1:

**Comment by mistydemeo** [comment]
Merged with an additional fix, e82d3afb9698395c390d3c894bad6584cfbfea01.

**Pull request merged**
