### PR TITLE
Update METS to encode in UTF-8 instead of ASCII

### PR DESCRIPTION
**Pull request by Hwesta**
Add xml declaration and UTF-8 encoding to all METS and XML files created.

Refs redmine 10629

### CODE REVIEW

**Comment by sevein** [comment]
👍

**Comment by Hwesta** [comment]
This may need to be backported to stable/1.6.x

**Comment by jrwdunham** [comment]
backported to stable/1.6.x as 89f83d1a2494b81ca3851b564fecf26cd2f27727

**Comment by nickwilkinson** [comment]
[Update METS to encode in UTF-8 instead of ASCII](https://trello.com/c/vHBToGP4/8-update-mets-to-encode-in-utf-8-instead-of-ascii)

**Pull request merged**
