### PR TITLE
base64: escape invalid UTF-8 characters before encoding

### PR DESCRIPTION
**Pull request by mistydemeo**
Fixes #9324.

### CODE REVIEW

**Comment by mistydemeo** [comment]
At some point I'd like to turn our vendored base64 file into an ES6 module that can be canonically stored in one repository, but we're not there yet.

**Comment by Hwesta** [comment]
That's pretty magic, but it works. :+1:

**Comment by Hwesta** [comment]
Cherry picked to 1.5 as da70663df0d9bfc91b23df4839bc61992c39353a and 1.4 as f1d3d80aeef587004d9b220dd58d40322f53a593

**Comment by mistydemeo** [comment]
If this got cherry-picked into a stable branch, should I just merge it into qa/1.x now?

**Comment by Hwesta** [comment]
Yup.

**Pull request merged**
