### PR TITLE
Remove unused Elasticsearch backup code

### PR DESCRIPTION
**Pull request by mistydemeo**
Closes #8076.

### CODE REVIEW

**Comment by mistydemeo** [comment]
The script to restore from this backup is in archivematica-devtools; PR there at artefactual/archivematica-devtools#5.

**Comment by Hwesta** [comment]
Update SQL to drop ElasticsearchIndexBackup?

**Comment by mistydemeo** [comment]
I'm fine with leaving the empty table personally, especially since I don't want to drop data users might have actually stored (assuming this was ever used).

**Comment by Hwesta** [comment]
I guess there's no model for it, so when we switch to using the ORM to create things it'll stop existing then.

:+1:

**Pull request closed without merging**
